/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import DAO.KhuVucDAO;
import DAO.MayTinhDAO;
import DAO.NapTheDAO;
import DAO.TaiKhoanDAO;
import DAO.ThongKeDonHangDAO;
import DAO.ThongKeTaiKhoanDAO;
import Entity.MayTinh;
import Entity.ThongKeTaiKhoan;
import Entity.TaiKhoan;
import Entity.ThongKeDonHang;
import Entity.KhuVucMay;
import Entity.NapThe;
import Utils.KetNoiDB;
import Utils.XImage;
import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maximus
 */
public class TrangChuQuanLy extends javax.swing.JFrame {

    DefaultTableModel Tmodel;

    /**
     * Creates new form TrangChuQuanLy
     */
    public TrangChuQuanLy() {
        this.preInit();
        initComponents();
        this.changeColor();
        this.load2Table();
        this.loadThongKeTaiKhoan();
        this.loadDoanhThuMon();
        this.loadComboChoice();
        this.loadTrangThai();
        this.loadNapThe();
        this.loadkhuvuc();
        this.updateTable();
        this.loadPC();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblXinChao = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        lblVaiTro = new javax.swing.JLabel();
        cboRole = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lblMatKhau = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSoDu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSdt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtHoten = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabThong_ke_tai_khoan = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabDoanhThuMon = new javax.swing.JTable();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboKhuvuc = new javax.swing.JComboBox<>();
        txtPCname = new javax.swing.JTextField();
        btnThem1 = new javax.swing.JButton();
        btnSua1 = new javax.swing.JButton();
        btnXoa1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPC = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtGiaPC = new javax.swing.JTextField();
        btnThem2 = new javax.swing.JButton();
        btnSua2 = new javax.swing.JButton();
        btnXoa2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblKhuvuc = new javax.swing.JTable();
        txtTenKhu = new javax.swing.JTextField();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        btnXacNhan = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblNapThe = new javax.swing.JTable();
        cboTrangThai = new javax.swing.JComboBox<>();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblDonHang = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        btnLuu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblXinChao.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblXinChao.setText("<< Xin chào Admin ! >>");

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        txtUsername.setBackground(new java.awt.Color(255, 255, 255));
        txtUsername.setForeground(new java.awt.Color(255, 153, 153));
        txtUsername.setSelectionColor(new java.awt.Color(255, 153, 102));

        lblVaiTro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblVaiTro.setText("Vai trò");

        cboRole.setBackground(new java.awt.Color(255, 153, 153));
        cboRole.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cboRole.setForeground(new java.awt.Color(255, 153, 153));
        cboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khách hàng", "Admin" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Tên đăng nhập");

        lblMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMatKhau.setText("Mật khẩu");

        txtPass.setBackground(new java.awt.Color(255, 255, 255));
        txtPass.setForeground(new java.awt.Color(255, 153, 153));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Số dư");

        txtSoDu.setBackground(new java.awt.Color(255, 255, 255));
        txtSoDu.setForeground(new java.awt.Color(255, 153, 153));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("SDT");

        txtSdt.setBackground(new java.awt.Color(255, 255, 255));
        txtSdt.setForeground(new java.awt.Color(255, 153, 153));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Họ tên");

        txtHoten.setBackground(new java.awt.Color(255, 255, 255));
        txtHoten.setForeground(new java.awt.Color(255, 153, 153));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Email");

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setForeground(new java.awt.Color(255, 153, 153));

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        btnThem.setBackground(new java.awt.Color(255, 255, 255));
        btnThem.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 153, 153));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Them.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel2.add(btnThem);

        btnSua.setBackground(new java.awt.Color(255, 255, 255));
        btnSua.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 153, 153));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Sua.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel2.add(btnSua);

        btnXoa.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 153, 153));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Xoa.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel2.add(btnXoa);

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id tài khoản", "Vai trò", "Tên đăng nhập", "Mật khẩu", "Số dư", "SDT", "Họ tên", "Email"
            }
        ));
        tblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblUser);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblVaiTro)
                                .addGap(29, 29, 29)
                                .addComponent(cboRole, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMatKhau)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPass)
                                    .addComponent(txtSdt)
                                    .addComponent(txtEmail))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(txtSoDu)
                            .addComponent(txtHoten))
                        .addGap(32, 32, 32))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVaiTro)
                    .addComponent(cboRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMatKhau)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(txtSoDu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        jTabbedPane2.addTab("CRUD tài khoản ", jPanel1);

        jTabbedPane1.addTab("Quản lý tài khoản", jTabbedPane2);

        TabThong_ke_tai_khoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID tài khoản", "Họ tên", "Số dư"
            }
        ));
        jScrollPane2.setViewportView(TabThong_ke_tai_khoan);

        jTabbedPane3.addTab("Thống kê tài khoản", jScrollPane2);

        tabDoanhThuMon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID sản phẩm", "Tên sản phẩm", "Số lượng đã bán", "Tổng doanh thu"
            }
        ));
        jScrollPane1.setViewportView(tabDoanhThuMon);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Doanh thu món", jPanel4);

        jTabbedPane1.addTab("Thống kê", jTabbedPane3);

        jLabel1.setText("Tên máy");

        jLabel2.setText("Khu vực");

        cboKhuvuc.setBackground(new java.awt.Color(255, 255, 255));
        cboKhuvuc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cboKhuvuc.setForeground(new java.awt.Color(255, 153, 153));
        cboKhuvuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboKhuvucActionPerformed(evt);
            }
        });

        txtPCname.setBackground(new java.awt.Color(255, 255, 255));
        txtPCname.setForeground(new java.awt.Color(255, 153, 153));
        txtPCname.setSelectionColor(new java.awt.Color(255, 153, 102));

        btnThem1.setBackground(new java.awt.Color(255, 255, 255));
        btnThem1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnThem1.setForeground(new java.awt.Color(255, 153, 153));
        btnThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Them.png"))); // NOI18N
        btnThem1.setText("Thêm");
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });

        btnSua1.setBackground(new java.awt.Color(255, 255, 255));
        btnSua1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnSua1.setForeground(new java.awt.Color(255, 153, 153));
        btnSua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Sua.png"))); // NOI18N
        btnSua1.setText("Sửa");
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });

        btnXoa1.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnXoa1.setForeground(new java.awt.Color(255, 153, 153));
        btnXoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Xoa.png"))); // NOI18N
        btnXoa1.setText("Xóa");
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });

        tblPC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ", "Tên máy", "Khu vực"
            }
        ));
        tblPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPCMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblPC);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPCname, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cboKhuvuc, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(btnSua1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPCname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cboKhuvuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(134, 134, 134)
                .addComponent(jScrollPane4)
                .addGap(122, 122, 122))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap(178, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnSua1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoa1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(592, Short.MAX_VALUE)))
        );

        jTabbedPane4.addTab("Quản lý máy", jPanel3);

        jLabel4.setText("Giá khu vực");

        jLabel9.setText("Tên khu vực");

        txtGiaPC.setBackground(new java.awt.Color(255, 255, 255));
        txtGiaPC.setForeground(new java.awt.Color(255, 153, 153));
        txtGiaPC.setSelectionColor(new java.awt.Color(255, 153, 102));

        btnThem2.setBackground(new java.awt.Color(255, 255, 255));
        btnThem2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnThem2.setForeground(new java.awt.Color(255, 153, 153));
        btnThem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Them.png"))); // NOI18N
        btnThem2.setText("Thêm");
        btnThem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem2ActionPerformed(evt);
            }
        });

        btnSua2.setBackground(new java.awt.Color(255, 255, 255));
        btnSua2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnSua2.setForeground(new java.awt.Color(255, 153, 153));
        btnSua2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Sua.png"))); // NOI18N
        btnSua2.setText("Sửa");
        btnSua2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua2ActionPerformed(evt);
            }
        });

        btnXoa2.setBackground(new java.awt.Color(255, 255, 255));
        btnXoa2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnXoa2.setForeground(new java.awt.Color(255, 153, 153));
        btnXoa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Xoa.png"))); // NOI18N
        btnXoa2.setText("Xóa");
        btnXoa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa2ActionPerformed(evt);
            }
        });

        tblKhuvuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID khu vực", "Giá khu vực", "Tên khu vực"
            }
        ));
        tblKhuvuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhuvucMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblKhuvuc);

        txtTenKhu.setBackground(new java.awt.Color(255, 255, 255));
        txtTenKhu.setForeground(new java.awt.Color(255, 153, 153));
        txtTenKhu.setSelectionColor(new java.awt.Color(255, 153, 102));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(txtGiaPC, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtTenKhu, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnThem2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(btnSua2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(btnXoa2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGiaPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenKhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(135, 135, 135)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addGap(121, 121, 121))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap(178, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnSua2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoa2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThem2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(592, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 865, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 797, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane4.addTab("Quản lý khu vực", jPanel5);

        jTabbedPane1.addTab("Quản lý khu máy", jTabbedPane4);

        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        tblNapThe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID nạp tiền", "Tên tài khoản", "Mệnh giá", "Trạng thái"
            }
        ));
        jScrollPane7.setViewportView(tblNapThe);

        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane7)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXacNhan)
                    .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane5.addTab("Nạp tiền", jPanel7);

        jTabbedPane1.addTab("Quản lý nạp tiền", jTabbedPane5);

        jLabel10.setText("Đơn hàng số: ");

        jLabel11.setText("Trạng thái đơn hàng: ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setText("Thời gian đặt hàng: ");

        jLabel13.setText("Khách hàng: ");

        jLabel14.setText("00:00:00 00/00");

        jLabel15.setText("ID01");

        tblDonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Sản Phẩm", "Số Lượng", "Tổng Giá"
            }
        ));
        jScrollPane6.setViewportView(tblDonHang);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane8.setViewportView(jTextArea1);

        jLabel16.setText("Ghi chú đơn hàng: ");

        btnLuu.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        btnLuu.setText("Lưu");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(393, 393, 393))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel14)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel15))))
                        .addContainerGap(87, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLuu)
                        .addGap(101, 101, 101))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel10)
                .addGap(34, 34, 34)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(jLabel14)
                        .addComponent(jLabel13)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnLuu)))
                .addContainerGap(241, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Đơn 01", jPanel8);

        jTabbedPane1.addTab("Quán lý đơn hàng", jTabbedPane6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblXinChao)
                .addGap(318, 318, 318))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 968, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblXinChao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean isAllValid() {
        String username = txtUsername.getText();
        String password = txtPass.getText();
        String soDu = txtSoDu.getText();
        String phoneNum = txtSdt.getText();
        String hoTen = txtHoten.getText();
        String email = txtEmail.getText();
        if (username.isBlank() == true || password.isBlank() == true || soDu.isBlank() == true || phoneNum.isBlank() == true || hoTen.isBlank() == true || email.isBlank() == true) {
            return false;
        } else {
            return true;
        }
    }

    private void loadComboChoice(){
        KhuVucDAO khuVucDAO = new KhuVucDAO();
        List<String> lstKhuVuc = new ArrayList<>();
        lstKhuVuc.clear();
        cboKhuvuc.removeAllItems();
        lstKhuVuc = khuVucDAO.getListKhuVuc();
        for (String string : lstKhuVuc) {
            cboKhuvuc.addItem(string);
        }
    }
    private void loadTrangThai() {
        NapTheDAO ntDAO = new NapTheDAO();
        List<String> lstTrangThai = new ArrayList<>();
        cboTrangThai.removeAllItems();
        lstTrangThai = ntDAO.getTrangThai();
        for (String string : lstTrangThai) {
            cboTrangThai.addItem(string);
        }
    }
    private TaiKhoan getInfo() {
        String username = txtUsername.getText();
        String password = txtPass.getText();
        int soDu = Integer.parseInt(txtSoDu.getText());
        String phoneNum = txtSdt.getText();
        String hoTen = txtHoten.getText();
        String email = txtEmail.getText();
        boolean vaiTro = String.valueOf(cboRole.getSelectedItem()).equals("Admin") ? true : false;
        return new TaiKhoan(vaiTro, username, password, soDu, phoneNum, email, hoTen);
    }

    private void changeColor() {
        Timer timer = new Timer(1000, e -> {
            Random rand = new Random();
            Color randomColor = new Color(rand.nextInt(256), rand.nextInt(256), rand.nextInt(256));
            lblXinChao.setForeground(randomColor);
        });
        timer.start();
    }

    private void updateTable() {
        Timer timer = new Timer(3000, e -> {
            this.load2Table();
            this.loadThongKeTaiKhoan();
            this.loadDoanhThuMon();
            this.loadComboChoice(); 
            this.loadkhuvuc();
            this.loadPC();
        });
        timer.start();
    }

    private void load2Table() {
        Tmodel = (DefaultTableModel) tblUser.getModel();
        Tmodel.setRowCount(0);
        List<TaiKhoan> lstTk = new ArrayList<>();
        lstTk.clear();
        TaiKhoanDAO tkDAO = new TaiKhoanDAO();
        lstTk = tkDAO.getData();
        for (TaiKhoan taiKhoan : lstTk) {
            Object[] tk_add = new Object[]{tkDAO.getSTT(taiKhoan.getSdt()), taiKhoan.isVai_tro() ? "Admin" : "Khách hàng", taiKhoan.getTen_dang_nhap(), taiKhoan.getMat_khau(), taiKhoan.getSo_du(), taiKhoan.getSdt(), taiKhoan.getHo_ten(), taiKhoan.getEmail()};
            Tmodel.addRow(tk_add);
        }
        tblUser.setModel(Tmodel);
    }

    public void loadThongKeTaiKhoan() {
        DefaultTableModel tabThongKe = (DefaultTableModel) this.TabThong_ke_tai_khoan.getModel();
        tabThongKe.setRowCount(0);
        ThongKeTaiKhoanDAO TKTKDAO = new ThongKeTaiKhoanDAO();
        List<ThongKeTaiKhoan> TKTKLst = TKTKDAO.ThongTinThongKeTK();
        for (ThongKeTaiKhoan ThongKe : TKTKLst) {
            tabThongKe.addRow(new Object[]{
                ThongKe.getId_tk(),
                ThongKe.getHo_ten(),
                ThongKe.getSo_du()
            });
        }
    }

    public void loadDoanhThuMon() {
        DefaultTableModel tabDoanhThu = (DefaultTableModel) this.tabDoanhThuMon.getModel();
        tabDoanhThu.setRowCount(0);
        ThongKeDonHangDAO TKDHdao = new ThongKeDonHangDAO();
        List<ThongKeDonHang> TKDHLst = TKDHdao.ThongTinThongKeDonHang();
        for (ThongKeDonHang DoanhThu : TKDHLst) {
            tabDoanhThu.addRow(new Object[]{
                DoanhThu.getId_san_pham(),
                DoanhThu.getTen_sp(),
                DoanhThu.getSo_luong_ban(),
                DoanhThu.getTong_doanh_thu()
            });
        }
    }
    public void loadkhuvuc(){
        DefaultTableModel tblKhuvuc = (DefaultTableModel) this.tblKhuvuc.getModel();
        tblKhuvuc.setRowCount(0);
        KhuVucDAO khuvucDAO = new KhuVucDAO();
        List<KhuVucMay> KhuMaylst = new ArrayList<>();
        KhuMaylst = khuvucDAO.readKhuvuc();
        for (KhuVucMay khumay : KhuMaylst){
            tblKhuvuc.addRow(new Object[]{
                khuvucDAO.getId(khumay.getTen_khu_vuc()),
                khumay.getGia_khu_vuc(),
                khumay.getTen_khu_vuc()
            });
        }
    }
    public void loadNapThe() {
        DefaultTableModel tblNapThe = (DefaultTableModel) this.tblNapThe.getModel();
        tblNapThe.setRowCount(0);
        NapTheDAO ntDAO = new NapTheDAO();
        List<NapThe> lstNapThe = new ArrayList<>();
        lstNapThe = ntDAO.readNapThe();
        for (NapThe napThe : lstNapThe) {
            tblNapThe.addRow(new Object[]{
                ntDAO.getIdNap(napThe.getMenhGia()),
                napThe.getMenhGia(),
                napThe.getId_tk(),
                napThe.isTrangThai() ? "Hủy bỏ" : "Thành công"});
        }
    }
    private void loadPC(){
        DefaultTableModel tabMayTinh = (DefaultTableModel) tblPC.getModel();
        tabMayTinh.setRowCount(0);
        MayTinhDAO mtDAO = new MayTinhDAO();
        KhuVucDAO kvDAO = new KhuVucDAO();
        List<MayTinh> lstPC = mtDAO.parseListPC();
        for (MayTinh mayTinh : lstPC) {
            tabMayTinh.addRow(new Object[]{mtDAO.getIDPC(mayTinh.getTen_may()),mayTinh.getTen_may(), kvDAO.getTenKhuVuc(mayTinh.getId_khu_vuc())});
        }
    }
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String sdt = txtSdt.getText();
        int check = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn xóa ?");
        if (check == JOptionPane.YES_OPTION) {
            TaiKhoanDAO tkDAO = new TaiKhoanDAO();
            tkDAO.deleteAccount(sdt);
            JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Thao tác bị hủy bởi người dùng");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        int check = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn thêm tài khoản không ?");
        if (check == JOptionPane.YES_OPTION) {
            boolean validResult = this.isAllValid();
            if (validResult == true) {
                try (Connection conn = KetNoiDB.getConnect()) {
                    TaiKhoan tkAdd = this.getInfo();
                    TaiKhoanDAO tkDAO = new TaiKhoanDAO();
                    tkDAO.addAccount(tkAdd);
                    JOptionPane.showMessageDialog(rootPane, "Thêm tài khoản thành công");
                    this.load2Table();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "An error has occurred: " + e);
                    e.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng không bỏ trống các ô !");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Thao tác bị hủy bởi người dùng");
        }
    }//GEN-LAST:event_btnThemActionPerformed


    private void tblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserMouseClicked
        // TODO add your handling code here:
        int row = tblUser.getSelectedRow();
        if (row != -1) {
            txtUsername.setText(tblUser.getValueAt(row, 2).toString());
            txtPass.setText(tblUser.getValueAt(row, 3).toString());
            txtSoDu.setText(tblUser.getValueAt(row, 4).toString());
            txtSdt.setText(tblUser.getValueAt(row, 5).toString());
            txtHoten.setText(tblUser.getValueAt(row, 6).toString());
            txtEmail.setText(tblUser.getValueAt(row, 7).toString());

            String VT = tblUser.getValueAt(row, 1).toString();
            cboRole.setSelectedItem(VT);
        }
    }//GEN-LAST:event_tblUserMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int check = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn sửa không ?");
        if (check == JOptionPane.YES_OPTION) {
            TaiKhoan tkUpd = this.getInfo();
            TaiKhoanDAO tkDAO = new TaiKhoanDAO();
            tkDAO.updateAccount(tkUpd);
            JOptionPane.showMessageDialog(rootPane, "Update thành công");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Thao tác bị hủy bởi người dùng");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
        // TODO add your handling code here:
        String tenMay;
        tenMay = txtPCname.getText();
        String tenKhuVuc = String.valueOf(cboKhuvuc.getSelectedItem());
        if(tenMay.isBlank() == false){
            int check = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn thêm máy không ?");
            if (check == JOptionPane.YES_OPTION){
                KhuVucDAO khDAO = new KhuVucDAO();
                MayTinhDAO mtDAO = new MayTinhDAO();
                MayTinh mtNew = new MayTinh(tenMay, khDAO.getIDKhuVuc(tenKhuVuc));
                mtDAO.AddPC(mtNew);
                JOptionPane.showMessageDialog(rootPane, "Thêm máy thành công");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Thao tác bị hủy bởi người dùng");
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Vui lòng không để trống ô điền");
        }
    }//GEN-LAST:event_btnThem1ActionPerformed

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSua1ActionPerformed

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoa1ActionPerformed

    private void tblPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPCMouseClicked
        // TODO add your handling code here:
        int currentRow = tblPC.getSelectedRow();
    }//GEN-LAST:event_tblPCMouseClicked

    private void btnThem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem2ActionPerformed
        // TODO add your handling code here:
        String tenkhuvuc = txtTenKhu.getText();
        String giakhu = txtGiaPC.getText();
        if(tenkhuvuc.isEmpty() == true || giakhu.isEmpty() == true){
            JOptionPane.showMessageDialog(rootPane, "Nhập thêm");
        }else{
            KhuVucMay khumay = new KhuVucMay(tenkhuvuc, Integer.parseInt(giakhu));
        
            KhuVucDAO khuvucDAO = new KhuVucDAO();
            khuvucDAO.addKhuvucPC(khumay);
            JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
        }
    }//GEN-LAST:event_btnThem2ActionPerformed

    private void btnSua2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua2ActionPerformed
        // TODO add your handling code here:
        String tenkhuvuc = txtTenKhu.getText();
        String giakhu = txtGiaPC.getText();
        if(tenkhuvuc.isEmpty() == true || giakhu.isEmpty() == true){
            JOptionPane.showMessageDialog(rootPane, "Nhập thiếu");
        }else{
            KhuVucMay khumay = new KhuVucMay(tenkhuvuc, Integer.parseInt(giakhu));
        
            KhuVucDAO khuvucDAO = new KhuVucDAO();
            khuvucDAO.updateKhuVucPC(khumay);
            JOptionPane.showMessageDialog(rootPane, "Sửa thành công");
        }
    }//GEN-LAST:event_btnSua2ActionPerformed

    private void btnXoa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa2ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnXoa2ActionPerformed

    private void tblKhuvucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhuvucMouseClicked
        // TODO add your handling code here:
        int row = tblKhuvuc.getSelectedRow();
        if (row != -1) {
            txtGiaPC.setText(tblKhuvuc.getValueAt(row, 1).toString());
            txtTenKhu.setText(tblKhuvuc.getValueAt(row, 2).toString());
            }
    }//GEN-LAST:event_tblKhuvucMouseClicked

    private void cboKhuvucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboKhuvucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboKhuvucActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        String tenkhuvuc = txtTenKhu.getText();
        String giakhu = txtGiaPC.getText();
            NapThe napThe = new NapThe(WIDTH, HEIGHT, rootPaneCheckingEnabled);
            KhuVucMay khumay = new KhuVucMay(tenkhuvuc, Integer.parseInt(giakhu));
        
            KhuVucDAO khuvucDAO = new KhuVucDAO();
            khuvucDAO.updateKhuVucPC(khumay);
            JOptionPane.showMessageDialog(rootPane, "Sửa thành công");
        
    }//GEN-LAST:event_btnXacNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChuQuanLy().setVisible(true);
            }
        });
    }

    private void preInit() {
        this.setIconImage(XImage.getAppIcon());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabThong_ke_tai_khoan;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnSua2;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnThem2;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoa1;
    private javax.swing.JButton btnXoa2;
    private javax.swing.JComboBox<String> cboKhuvuc;
    private javax.swing.JComboBox<String> cboRole;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblVaiTro;
    private javax.swing.JLabel lblXinChao;
    private javax.swing.JTable tabDoanhThuMon;
    private javax.swing.JTable tblDonHang;
    private javax.swing.JTable tblKhuvuc;
    private javax.swing.JTable tblNapThe;
    private javax.swing.JTable tblPC;
    private javax.swing.JTable tblUser;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGiaPC;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtPCname;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtSoDu;
    private javax.swing.JTextField txtTenKhu;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
